version: "2.2"

services:
  selenium_hub:
    image: selenium/hub
    ports:
      - 4444:4444

  nexus_5_8.1:
    image: butomo1989/docker-android-x86-8.1
    privileged: true
    depends_on:
      - selenium_hub
    ports:
      - 6080:6080
    volumes:
      - $PWD/apks:/root/tmp/apks
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
